sudo: false

cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

language: scala

jdk:
  - oraclejdk8
  - openjdk11

env:
  - SCALA_VERSION=2.11.6
  - SCALA_VERSION=2.11.7
  - SCALA_VERSION=2.11.8
  - SCALA_VERSION=2.11.11
  - SCALA_VERSION=2.11.12
  - SCALA_VERSION=2.12.3
  - SCALA_VERSION=2.12.4
  - SCALA_VERSION=2.12.6
  - SCALA_VERSION=2.12.7
  - SCALA_VERSION=2.12.8
  - SCALA_VERSION=2.13.0-M5

# there's no better way it seems.. https://github.com/travis-ci/travis-ci/issues/1519
matrix:
  exclude:
    # scala 2.12+ requires jdk8
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.3
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.4
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.6
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.7
    - jdk: openjdk6
      env: SCALA_VERSION=2.12.8
    - jdk: openjdk6
      env: SCALA_VERSION=2.13.0-M5
    # 2.11.12 was the first Scala 2.11.x version to work on jdk11
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.6
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.7
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.8
    - jdk: openjdk11
      env: SCALA_VERSION=2.11.11

script:
  # Increasing ReservedCodeCacheSize minimizes scala compiler-interface compile times
  - sbt -J-XX:ReservedCodeCacheSize=256M ++$SCALA_VERSION test

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
